# Project-wide Gradle settings.
# For more details on how to configure your build, see
# http://www.gradle.org/docs/current/userguide/build_setting.html
#
# Specifies the JVM arguments used for the Gradle Daemon.
# Setting a longer duration for the daemon can help reduce startup time.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option can make builds faster in multi-module projects.
org.gradle.parallel=true
#
# AndroidX is the successor to the Android Support Library.
# It provides a set of libraries that can be used to build Android apps.
android.useAndroidX=true
#
# Automatically convert third-party libraries to use AndroidX.
# android.enableJetifier=true
#
# Use Kotlin DSL for build scripts.
# org.gradle.kotlin.dsl.precompiled.accessors=true
